### ISSUE TITLE
Random null reference exception when a check fails

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#338]
One of my tests is failing non-deterministically with a NullReferenceException in NFluent. Here is the stack trace:

   at NFluent.Helpers.ExceptionHelper.ExceptionScanner()
   at NFluent.Helpers.ExceptionHelper.InitCache(String patterns)
   at NFluent.Helpers.ExceptionHelper.get_Constructors()
   at NFluent.Helpers.ExceptionHelper.BuildException(String theMessage)
   at NFluent.Kernel.ExceptionReporter.ReportError(String message)
   at NFluent.Kernel.CheckLogic`1.EndCheck()
   at NFluent.Helpers.EqualityHelper.PerformEqualCheck[T,TE](ICheck`1 check, TE expected, IEqualityComparer comparer, Boolean useOperator)
   at NFluent.DecimalCheckExtensions.IsEqualTo(ICheck`1 check, Decimal expected)
This exception is quite fishy because null references should not occur in ExceptionScanner in normal conditions.The code mutates static objects without locks, so I suspected a thread-safety issue. I looked at the Exceptions dictionary and it was containing a null value for NUnit even thought the code never adds null values.

(see PR #337)

**Comment by dupdob** [comment]
Thanks for raising this, @ocoanet.
As this is a heisenbug, it is difficult, maybe even impossible, to design a regression test for this.
Hence, we need a clear understanding of how this bug happens before implementing a fix.
I fear a tentative fix may only displace the problem.

Let us try to have a working theory. Can you help me with a few questions:

1. Does this happen on a test suite where at least two tests fail (a race condition requires concurrent accesses to this code)?
2. Do you know the underlying architecture (Intel, AMD, other) (so we have the memory model)?

**Comment by ocoanet** [comment]
I felt that the new code was simply cleaner (by removing an unneeded member and by removing static mutable state) and thus that the change could be accepted as a natural refactoring.

Mutating a static dictionary without locks is a request for race conditions, and PR is an improvement in this regard.

However, I can try to reproduce the bug in a minimal unit test if you think it is required.
